arti/urls.py
from django.urls import path
from arti.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'arti'

urlpatterns = [
    path('', index, name='index'),
    path('galeri', galeri, name='galeri'),
    path('login', login_user, name='login'),
    path('register', register, name='register'),
    path('logout', logout_user, name='logout'),
    path('post-karya', post_karya, name='post_karya'),
    path('delete-karya/<karya_id>', delete_karya, name='delete_karya'),
    path('edit-karya/<karya_id>', edit_karya, name='edit_karya'),
]

beli_karya/urls.py
from django.urls import path
from beli_karya.views import *

app_name = 'beli_karya'

urlpatterns = [
    path('get-karyas', get_karyas, name='get_karyas'),
    path('', beli_karya, name='beli_karya')
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('arti.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('profileuser/', include('profileuser.urls')),
    path('beli_karya/', include('beli_karya.urls')),

]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

beli_karya/models.py
from django.db import models
from django.contrib.auth.models import User
from arti.models import Karya
# Create your models here.
class Transaksi(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE) 
    karya = models.ForeignKey(Karya,on_delete= models.CASCADE)

beli_karya/views.py
from django.urls import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from arti.models import Karya
from beli_karya.models import Transaksi
import json

# Create your views here.
def get_karyas(request):
    karyas = Karya.objects.all()
    lst = []
    for karya in karyas:
        transaksi = Transaksi.objects.filter(karya = karya)
        lst.append({
            'id': karya.pk,
            'judul': karya.judul,
            'kategori': karya.kategori,
            'deskripsi': karya.deskripsi,
            'user': karya.user.username,
            'harga': karya.harga,
            'tanggal': karya.tanggal.strftime('%d %B %Y'),
            'gambar': karya.gambar.url,
            'sudah_dibeli': transaksi.exists()
        })
    return HttpResponse(json.dumps(lst), content_type='application/json')

@login_required(login_url='/login')
def beli_karya(request):
    loggedin_user = request.user
    context = {
        'user': loggedin_user,
    }
    if request.method == 'POST':
        karyas = request.POST.getlist('karyas[]')
        print(karyas)
        for karya in karyas:
            k = Karya.objects.get(pk=int(karya))
            transaksi = Transaksi(user=loggedin_user, karya = k)
            transaksi.save()
    return render(request, 'beli-karya.html', context)

beli_karya/templates/beli-karya.html
{% extends 'base.html' %} {% load static %} {% block meta %}
<title>Post Karya</title>
<link rel="stylesheet" type="text/css" href="{% static 'css/beli-karya.css' %}"> {% endblock meta %} {% block content %}

<body>
    <nav class="topnav" id="myTopnav">
        <a href="{% url 'arti:index' %}">ARTi</a>
        <a href="{% url 'arti:galeri' %}">Galeri</a> {% if user.is_authenticated %}
        <a href="{% url 'arti:post_karya' %}">Post Karya</a>
        <a href="{% url 'beli_karya:beli_karya' %}" class="active">Beli Karya</a>
        <a href="leaderboard/">Leaderboard</a>
        <a href="profileuser/">Profile User</a> {% if user.is_superuser %}
        <a href="admin/">Admin</a> {% endif %}
        <a class="btn btn-danger" href="{% url 'arti:logout' %}" style="float: right;">Logout</a> {% else %}
        <a class="btn btn-info" href="{% url 'arti:login' %}" style="float: right;">Login</a>
        <a class="btn btn-warning" href="{% url 'arti:register' %}" style="float: right; margin-right: 20px">Register</a> {% endif %}
        <a href="javascript:void(0);" class="icon" onclick="myFunction()">
            <i class="fa fa-bars"></i>
        </a>
    </nav>
    <div class="beli-karya">
        <h2 class="text-center my-5 text-white bg-dark bg-opacity-50 w-25 mx-auto py-3 rounded-3">Beli Karya</h2>
        <div class="d-flex align-items-center justify-content-center">
            <form id="form" action="{% url 'beli_karya:beli_karya' %}" method="POST">
                {% csrf_token %}
                <div class="container justify-content-center row row-cols-1 row-cols-md-4 gap-3" id="container">
                </div>
                <br>
                <div class="d-flex justify-content-center">
                    <button type="submit" class="btn btn-success my-4 mx-auto w-25 fs-3">Beli</button>
                </div>
            </form>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <script>
        $(document).ready(function() {
            getKaryas();
        });

        function getKaryas() {
            $.ajax({
                url: "{% url 'beli_karya:get_karyas' %}",
                type: "GET",
                success: function(response) {
                    if (response.length == 0) {
                        $("#container").append("<p>Belum ada karya yang dijual</p>");
                    } else {
                        for (var i = 0; i < response.length; i++) {
                            // format harga
                            var harga = response[i].harga;
                            var reverse = harga.toString().split('').reverse().join('')
                            ribuan = reverse.match(/\d{1,3}/g);
                            ribuan = ribuan.join('.').split('').reverse().join('');
                            if (response[i].sudah_dibeli == false) {
                                html = ""
                                html += "<input type='checkbox' name='karya' value='"
                                html += response[i].id
                                html += "'"
                                html += "id='"
                                html += response[i].id
                                html += "'"
                                html += ">"
                                html += "<label for='" + response[i].id + "'' class='card px-4' style='width: 18rem;'>"

                                html += "<img src='"
                                html += response[i].gambar
                                html += "' class='card-img-top' alt='...'>"

                                html += "<div class='card-body'>"
                                html += "<h5 class='card-title'>"
                                html += response[i].judul
                                html += "</h5>"
                                html += "<p class='card-text'>"
                                html += response[i].deskripsi
                                html += "</p>"
                                html += "<p class='card-text'>Rp"
                                html += ribuan
                                html += ",-</p>"

                                html += "<p class='card-text'>Belum Dibeli </p>"

                                html += "</div>"
                                html += "</label>"
                                $("#container").append(html);

                                
                            } 
                            else {
                                html = ""
                                html += "<div class='card sold px-4' style='width: 18rem;'>"

                                html += "<img src='"
                                html += response[i].gambar
                                html += "' class='card-img-top' alt='...'>"

                                html += "<div class='card-body'>"
                                html += "<h5 class='card-title'>"
                                html += response[i].judul
                                html += "</h5>"
                                html += "<p class='card-text'>"
                                html += response[i].deskripsi
                                html += "</p>"
                                html += "<p class='card-text'>Rp"
                                html += ribuan
                                html += ",-</p>"

                                html += "<p class='card-text top-right-label'>Sold </p>"

                                html += "</div>"
                                html += "</div>"
                                $("#container").append(html);
                            }

                        }
                    }
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }

        $('#form').submit(function(e) {
            e.preventDefault();
            submitBeli();
        });

        function submitBeli() {
            var karyas = [];
            var karya = document.getElementsByName('karya');
            for (var i = 0; i < karya.length; i++) {
                if (karya[i].checked) {
                    karyas.push(parseInt(karya[i].value));
                }
            }
            console.log(karyas);
            $.ajax({
                url: "{% url 'beli_karya:beli_karya' %}",
                type: "POST",
                data: {
                    'karyas': karyas,
                    'csrfmiddlewaretoken': '{{ csrf_token }}'
                },
                success: function(response) {
                    location.reload();
                },
                error: function(error) {
                    console.log(error);
                }
            });
        }
    </script>
</body>
{% endblock content %}