arti/urls.py
from django.urls import path
from arti.views import *
from django.conf import settings
from django.conf.urls.static import static

app_name = 'arti'

urlpatterns = [
    path('', index, name='index'),
    path('galeri', galeri, name='galeri'),
    path('login', login_user, name='login'),
    path('register', register, name='register'),
    path('logout', logout_user, name='logout'),
    path('post-karya', post_karya, name='post_karya'),
    path('delete-karya/<karya_id>', delete_karya, name='delete_karya'),
    path('edit-karya/<karya_id>', edit_karya, name='edit_karya'),
]

profileuser/urls.py
from django.urls import path
from profileuser.views import *

app_name = 'profileuser'

urlpatterns = [
    path('', show_profile, name='show_profile'),
    path('edit/', add, name='add'),
    # path('json/', get_json, name='get_json'),
    path('edit/addimage/', image_request, name='image-request'),
    path('edit/addrecord/', show_edit_profile, name='show_edit_profile'),
    path('edit/profile-ajax/', show_ajax_profile, name='show_ajax_profile'),

]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('arti.urls')),
    path('leaderboard/', include('leaderboard.urls')),
    path('profileuser/', include('profileuser.urls')),
    path('beli_karya/', include('beli_karya.urls')),

]
if settings.DEBUG:  
        urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT) 

profileuser/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Profile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    username = models.TextField()
    email = models.TextField()
    phone = models.TextField()
    mobile = models.TextField()
    address = models.TextField()
    finish = models.BooleanField(default=False)

class UploadImage(models.Model): 
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True) 
    image = models.ImageField(upload_to='images')  
    
   

profileuser/forms.py
from django.db import models  
from django.forms import fields  
from .models import UploadImage  
from django import forms  
  
  
class UserImageForm(forms.ModelForm):  
    class Meta:  
        # To specify the model to be used to create form  
        model = UploadImage  
        # It includes all the fields of model  
        # fields = '__all__' 
        fields = ('image',) 

profileuser/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from profileuser.models import *
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.core import serializers
from django.template import loader
from django.urls import reverse
from profileuser.forms import UserImageForm
from django.contrib.auth.decorators import login_required
from arti.models import *  

# Create your views here.

@login_required(login_url='/login')
def show_profile(request):
    profile = Profile.objects.filter(user=request.user).last()
    profileimg = UploadImage.objects.filter(user=request.user).last()
    profileimg2 = Karya.objects.filter(user=request.user)

    template = loader.get_template('profile.html')

    context = {
        'changes' : profile,
        'img' : profileimg,
        'img2' : profileimg2,

    }
    return HttpResponse(template.render(context, request))

def add(request):
    profile = Profile.objects.filter(user=request.user).last()
    profileimg = UploadImage.objects.filter(user=request.user).last()
    profileimg2 = Karya.objects.filter(user=request.user)
    template = loader.get_template('add.html')

    context = {
        'changes' : profileValue,
        'img' : profileimg,
        'img2' : profileimg2,

    }
    return HttpResponse(template.render(context, request)) 

def show_edit_profile(request):
    username1 = request.POST['username']
    email1 = request.POST['email']
    phone1 = request.POST['phone']
    mobile1 = request.POST['mobile']
    address1 = request.POST['address']
    profile1 = Profile(
        user=request.user,
        username = username1,
        email = email1,
        phone = phone1,
        mobile = mobile1,
        address = address1)
        
    profile1.save()
    return HttpResponseRedirect(reverse('profileuser:show_profile'))

@login_required(login_url='/login')
def image_request(request):  
    if request.method == 'POST':  
        form = UserImageForm(request.POST, request.FILES)  
        if form.is_valid():
            form.instance.user = request.user  
            form.save()  
  
            # Getting the current instance object to display in the template  
            img_object = form.instance  
              
            return render(request, 'edit_profile.html', {'form': form, 'img_obj': img_object})  
    else:  
        form = UserImageForm()  
  
    return render(request, 'edit_profile.html', {'form': form})  

# def get_json(request):
#     dataprofile = Profile.objects.last()
#     return HttpResponse(serializers.serialize("json", dataprofile), content_type="application/json")

@login_required(login_url='/login')
def show_ajax_profile(request):
    profile = Profile.objects.filter(user=request.user).last()
    profileimg = UploadImage.objects.filter(user=request.user).last()     
    profileimg2 = Karya.objects.filter(user=request.user)
    template = loader.get_template('edit_ajax_profile.html')

    context = {
        'changes' : profile,
        'img' : profileimg,
        'img2' : profileimg2,
    }
    return HttpResponse(template.render(context, request))

    

profileuser/templates/add.html
<header>
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
</header>

<div class="container">
    <div class="main-body">
        <div class="row">
            <div class="col-lg-4">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex flex-column align-items-center text-center">
                            <img src="{{ img.image.url }}" alt="Admin" class="rounded-circle p-1 bg-primary" width="120" height="120">
                            <div class="mt-3">
                                <h4>{{changes.username}}</h4>
                                <p class="text-secondary mb-1">{{changes.email}}</p>
                                <p class="text-muted font-size-sm">{{changes.address}}</p>
                                <form action="addimage/" method="POST" enctype="multipart/form-data">  
                                    {% csrf_token %}  
                                    {{ form.as_p }}  
                                    <button type="submit" class="btn btn-primary">Add/Change Image</button>
                                </form>  
                              
                                {% if img_obj %}  
                                    <h3>Succesfully uploaded : {{ img_obj.caption }}</h3>  
                                    <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">  
                                {% endif %}  
                                
                            </div>
                        </div>
                        
                        </ul>
                    </div>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="card">
                    <div class="card-body">
                        <form action="addrecord/" method="POST">
                            {% csrf_token %}

                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Full Name</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name="username" value="{{changes.username}}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Email</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name="email" value="{{changes.email}}" >
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Phone</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name="phone" value="{{changes.phone}}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Mobile</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name="mobile" value="{{changes.mobile}}">
                                </div>
                            </div>
                            <div class="row mb-3">
                                <div class="col-sm-3">
                                    <h6 class="mb-0">Address</h6>
                                </div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="text" class="form-control" name="address" value="{{changes.address}}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-3"></div>
                                <div class="col-sm-9 text-secondary">
                                    <input type="submit" class="btn btn-primary px-4" value="Save Changes" >
                                </div>
                            </div>
                            
                        </form>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    
</div>

<style>
    body{
        background: #f7f7ff;
        margin-top:20px;
    }
    .card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid transparent;
    border-radius: .25rem;
    margin-bottom: 1.5rem;
    box-shadow: 0 2px 6px 0 rgb(218 218 253 / 65%), 0 2px 6px 0 rgb(206 206 238 / 54%);
}
.me-2 {
    margin-right: .5rem!important;
}
</style>

profileuser/templates/edit_ajax_profile.html
<div class="col-md-4 mb-3">
  <div id="kartup" class="card">
    <div id="kartup" class="card-body">
      <div class="d-flex flex-column align-items-center text-center">
        <img src="{{ img.image.url }}" alt="" class="rounded-circle p-1" width="120" height="120">
        <div class="mt-3">
          <h4>{{changes.username}}</h4>
          <p style="color:white">{{changes.email}}</p>
          <p style="color:white">{{changes.address}}</p>
          <p style="color:black" class="text-donate" >Total Donasi: ***</p>
          
        </div>
      </div>
    </div>
  </div>
  
</div>

<div class="col-md-8">
  <div id="cardu" class="card mb-3">
    <div class="card-body">
      <div class="row">
        <div class="col-sm-3">
          <h6 id="userp" class="mb-0">Full Name</h6>
        </div>
        <div class="col-sm-9">
          {% if changes %}
          {{ changes.username }}
          {% endif %}

        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 id="emailp" class="mb-0">Email</h6>
        </div>
        <div class="col-sm-9">
          {% if changes %}
          {{ changes.email }}
          {% endif %}

        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 id="phonep" class="mb-0">Phone</h6>
        </div>
        <div class="col-sm-9">
          {% if changes %}
          {{ changes.phone }}
          {% endif %}

        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 id="mobilep" class="mb-0">Mobile</h6>
        </div>
        <div class="col-sm-9">
          {% if changes %}
          {{ changes.mobile }}
          {% endif %}

        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-3">
          <h6 id="addressp" class="mb-0">Address</h6>
        </div>
        <div class="col-sm-9">
          {% if changes %}
          {{ changes.address }}
          {% endif %}

        </div>
      </div>
      <hr>
      <div class="row">
        <div class="col-sm-12">
          <a id="editbutton" class="btn btn-info " data-bs-toggle="modal" data-bs-target="#exampleModal">Edit</a>
        </div>
      </div>
    </div>
  </div>

  <div class="row gutters-sm">
    <!--  untuk loop gambar  -->
    {% for images in img2 %}
    <div class="col-sm-6 mb-3">
      <div id="kartupostan" class="card h-100">
        <div id="kartupostan" class="card-body">
          <img src="{{ images.gambar.url }}" loading="lazy" alt="" class="progress mb-3" style="height:100%; width: 100%">
          <div class="progress mb-3" style="height: 5px">
          </div>
        </div>
      </div>
    </div>
    
    <!--akhir dari loop -->
    {% endfor %}
  </div>

  <!-- modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">EDIT PROFILE</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <div id="kartuprofile" class="card">
        <div id="kartu" class="card-body">
            <div class="d-flex flex-column align-items-center text-center">
                <img src="{{ img.image.url }}" alt="" class="rounded-circle p-1" width="120" height="120">
                <div class="mt-3">
                    <h4>{{changes.username}}</h4>
                    <p>{{changes.email}}</p>
                    <p>{{changes.address}}</p>
                    <form action="edit/addimage/" method="POST" enctype="multipart/form-data">  
                        {% csrf_token %}  
                        {{ form.as_p }}  
                        <button id="changeimg" type="submit" class="btn btn-primary">Add/Change Image</button>
                    </form>  
                  
                    {% if img_obj %}  
                        <h3>Succesfully uploaded : {{ img_obj.caption }}</h3>  
                        <img src="{{ img_obj.image.url}}" alt="connect" style="max-height:300px">  
                    {% endif %}  
                    
                </div>
            </div>
            
            </ul>
        </div>
    </div>
              <form id="formodal" action="/profileuser/edit/addrecord/" method="POST">
                {% csrf_token %}
                
                <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input id="username" type="text" class="form-control" name="username" value="{{changes.username}}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input id="email" type="text" class="form-control" name="email" value="{{changes.email}}" >
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Phone</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input id="phone" type="text" class="form-control" name="phone" value="{{changes.phone}}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Mobile</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input id="mobile" type="text" class="form-control" name="mobile" value="{{changes.mobile}}">
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col-sm-3">
                        <h6 class="mb-0">Address</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        <input id="address" type="text" class="form-control" name="address" value="{{changes.address}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3"></div>
                    <div class="col-sm-9 text-secondary">
                        <input id="save" data-bs-dismiss="modal" type="button" class="btn btn-primary px-4" value="Save Changes" >
                    </div>
                </div>
                
            </form>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
<!-- batas modal -->



</div>
  
<style>

#editbutton{
  background-color: #383E56;
  color: white;
}

#kartupostan{
  border-radius: 25px;
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

.rounded-circle{
    background-image: url('/static/img/11.jpg');
}

.topnav {
    background-color: #333;
    margin-bottom: 20px;
    overflow: hidden;
    position: sticky;
    top: 0;
    z-index: 1;
}

.topnav a {
    float: left;
    display: block;
    color: #f2f2f2;
    text-align: center;
    padding: 14px 16px;
    text-decoration: none;
    font-size: 17px;
}

.topnav a:hover {
    background-color: #ddd;
    color: black;
    transition: all .5s ease 0s;
}

.topnav a.active {
    background-color: #04AA6D;
    color: white;
}

.topnav .icon {
    display: none;
}

@media screen and (max-width: 687px) {
    .topnav a:not(:first-child) {
        display: none;
    }

    .topnav a.icon {
        float: right;
        display: block;
    }
}

@media screen and (max-width: 687px) {
    .topnav.responsive {
        position: sticky;
        top: 0;
      }

    .topnav.responsive a.icon {
        position: absolute;
        right: 0;
        top: 0;
    }

    .topnav.responsive a {
        float: none;
        display: block;
        text-align: left;
    }
}

@import url('https://fonts.googleapis.com/css2?family=Asap&display=swap');

#kartuprofile{
  border-radius: 25px;
}

#save{
  background-image: url('/static/img/bg-index.jpg');
}

#changeimg{
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

#cardu{
  border-radius: 25px;
  background: linear-gradient(-45deg, purple, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
  color: white;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

#examplemodal{
  color: white;
}

#kartu{
  background-image: url('/static/img/bg-index.jpg');
  border-radius: 25px;
}

#kartup{
  border-radius: 25px;
  background: linear-gradient(-45deg, purple, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
  color: white;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    } 
}

#formodal{
  margin-top: 40px;
  border-radius: 25px;
}


.modal-content{
  background: linear-gradient(-45deg, #ee7752, #e73c7e, #23a6d5, #23d5ab);
  background-size: 400% 400%;
  animation: gradient 15s ease infinite;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

.warna-body{
  margin-top:0px;
  background-image: url('/static/img/pexels-anni-roenkae-2156881.jpg');
}

body{
  margin-top:20px;
  color: #1a202c;
  text-align: left;
  background-color: black;    
}

.main-body {
    padding: 15px;
    
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

.card {
    box-shadow: 0 1px 3px 0 rgba(0,0,0,.1), 0 1px 2px 0 rgba(0,0,0,.06);
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid rgba(0,0,0,.125);
    border-radius: .25rem;
}

.card-body {
    flex: 1 1 auto;
    min-height: 1px;
    padding: 1rem;
}

.gutters-sm {
    margin-right: -8px;
    margin-left: -8px;
}

.gutters-sm>.col, .gutters-sm>[class*=col-] {
    padding-right: 8px;
    padding-left: 8px;
}
.mb-3, .my-3 {
    margin-bottom: 1rem!important;
}

.bg-gray-300 {
    background-color: #e2e8f0;
}
.h-100 {
    height: 100%!important;
}
.shadow-none {
    box-shadow: none!important;
}
p.text-donate{
  padding:3px;
  margin: 5px;
  background-color: greenyellow;
  border-radius: 50px;
}
</style>
    
<script>
  $(document).ready(function(){
    $("#save").click(function(){
      $.ajax({
        type: "POST",
        url: "/profileuser/edit/addrecord/",
        data: {
          "csrfmiddlewaretoken":"{{csrf_token}}",
          "username": $("#username").val(),
          "email": $("#email").val(),
          "phone": $("#phone").val(),
          "mobile": $("#mobile").val(),
          "address": $("#address").val(),
        }
        
      })
      alert("update success");
      $.ajax({
        type: "GET",
        url: "{% url 'profileuser:show_ajax_profile' %}",
        success: function(data){
          $("#body").html(data)
          // $("#userp").html(data.username);
          // $("#emailp").html(data.email);
          // $("phonep").html(data.phone);
          // $("#mobilep").html(data.mobile);
          // $("#addressp").html(data.address);
        }
      })

    })
  })
</script>

profileuser/templates/edit_profile.html
{% load static %}

<header>
    <!-- CSS only -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">    
</header>

<body class="warna-body">
    
    <div class="container">
        <div class="main-body">
            <div class="row">
                <div class="col-lg-4">
                    <div id="kartupro" class="card">
                        <div class="card-body">
                            <div class="d-flex flex-column align-items-center text-center">
                                <img src="{{ img_obj.image.url }}" alt="" class="rounded-circle p-1" width="120" height="120">
                                <div class="mt-3">
                                    <h4>{{changes.username}}</h4>
                                    <p class="text-secondary mb-1">{{changes.email}}</p>
                                    <p class="text-muted font-size-sm">{{changes.address}}</p>
    
                                    <!-- form di bawah untuk menyimpan foto di dalam database -->
                                    <form action="" method="POST" enctype="multipart/form-data">  
                                        {% csrf_token %}  
                                        {{ form.as_p }}
                                        <table boarder="1">
                                            <tr>
                                                <button type="submit" class="btn btn-primary">Save</button><br>
    
                                            </tr>
                                            
                                        </table>  
                                    </form>
    
                                    <!-- kemudian, form di bawah ini bertujuan untuk mengembalikan ke halaman tempat pemanggilan Add/Change photo -->
                                    <form action="/profileuser/">
                                        <table boarder="1">
                                            <tr>
                                                <button type="submit" class="btn btn-primary">Back</button><br>
    
                                            </tr>
                                            
                                        </table>  
                                    </form>  
                                  
                                    {% if img_obj %}  
                                        <h3>Succesfully uploaded : {{ img_obj.caption }}</h3>  
                                        <img src="{{img_obj.image.url}}" alt="connect" style="max-height:300px;max-width:300px;">  
                                    {% endif %}  
                                    <!-- <button class="btn btn-primary">Follow</button> -->
                                    <!-- <button class="btn btn-outline-primary">Message</button> -->
                                </div>
                            </div>
                        </div>
                    </div>
                
            </div>
        </div>
        
    </div>
</body>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-iYQeCzEYFbKjA/T2uDLTpkwGzCiq6soy8tYaI1GyVh/UjpbCx/TYkiZhlZB6+fzT" crossorigin="anonymous">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">    

<style>

.rounded-circle{
    background-image: url('/static/img/11.jpg');

}

form{
    color: white;
}

#kartupro{
    background: linear-gradient(-45deg, rgb(26, 4, 43), rgb(89, 26, 112), rgb(59, 33, 130));
    background-size: 400% 400%;
    animation: gradient 5s ease infinite;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

body{
    background: #f7f7ff;
    margin-top:20px;
}

.main-body {
    padding: 15px;
    background: linear-gradient(-45deg,rgb(30, 7, 54), #5f1995, #a03eca ,rgb(215, 55, 240), rgb(95, 154, 222), rgb(41, 127, 130), rgb(27, 89, 99));
    background-size: 400% 400%;
    animation: gradient 5s ease infinite;
    height: 100vh;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

.warna-body{
  margin-top:20px;
  background: linear-gradient(-45deg,rgb(30, 7, 54), #5f1995, #a03eca ,rgb(215, 55, 240), rgb(95, 154, 222), rgb(41, 127, 130), rgb(27, 89, 99));
  background-size: 400% 400%;
  animation: gradient 5s ease infinite;
  height: 100vh;
}
@keyframes gradient {
    0% {
        background-position: 0% 50%;
    }
 
    50% {
        background-position: 100% 50%;
    }
 
    100% {
        background-position: 0% 50%;
    }
}

.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: border-box;
    border: 0 solid transparent;
    border-radius: .25rem;
    margin-bottom: 1.5rem;
    box-shadow: 0 2px 6px 0 rgb(218 218 253 / 65%), 0 2px 6px 0 rgb(206 206 238 / 54%);
}
.me-2 {
    margin-right: .5rem!important;
}
</style>